# Generated by Django 4.1 on 2022-08-25 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComunicacaoDePerda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_produtor', models.CharField(max_length=100, null=True)),
                ('email_produtor', models.CharField(max_length=100, null=True)),
                ('cpf_produtor', models.CharField(max_length=14, null=True)),
                ('lat_lavoura', models.DecimalField(decimal_places=16, max_digits=22, null=True)),
                ('lon_lavoura', models.DecimalField(decimal_places=16, max_digits=22, null=True)),
                ('tipo_lavoura', models.CharField(max_length=50, null=True)),
                ('data_colheita', models.DateField()),
                ('evento', models.CharField(choices=[('1', 'CHUVA EXCESSIVA'), ('2', 'GEADA'), ('3', 'GRANIZO'), ('4', 'SECA'), ('5', 'VENDAVAL'), ('6', 'RAIO')], max_length=1, null=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Comunicação de perda',
                'verbose_name_plural': 'Comunicações de perda',
                'ordering': ['-atualizado_em'],
            },
        ),
    ]
